app:
    resource: "@AppBundle/Controller/"
    type:     annotation

blog:
    path: "/blog/{id}"
    defaults:
        _controller: "AppBundle:Blog:view"
        _extra: 'extra attribute'
    requirements:
        id: \d
