# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    acme.wikisearch.api: 'https://en.wikipedia.org/w/api.php?action=query&list=search&format=json&srsearch='

services:
    acme.article_repository:
        class: AppBundle\Repository\ArticleRepository
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    acme.wikisearch:
        class: Wikipedia\Engine
        arguments:
            - '@acme.article_repository'
            - '@acme.wikiclient'
            - '%acme.wikisearch.api%'

    acme.wikiclient:
        class: Wikipedia\Client

    acme.useragent_listener:
        class: AppBundle\Listener\UserAgentListener
        arguments: [ '@agent' ]
        tags:
            - { name: kernel.event_listener, event: kernel.request }
            - { name: kernel.event_subscriber }

    agent:
        class: Jenssegers\Agent\Agent

    acme.view_listener:
        class: AppBundle\Listener\ViewListener
        tags:
            - { name: kernel.event_listener, event: kernel.view }

    acme.article_converter:
        class: AppBundle\Request\ParamConverter\ArticleConverter
        arguments:
            - '@acme.article_repository'
        tags:
            - { name: request.param_converter, priority: 0, converter: article_converter }

    acme.twig_extension:
        class: AppBundle\Twig\AcmeExtension
        tags:
            - { name: twig.extension }
