# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    acme.wikisearch.api: 'https://en.wikipedia.org/w/api.php?action=query&list=search&format=json&srsearch='

services:
    acme.article_repository:
        class: AppBundle\Repository\ArticleRepository
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    acme.wikisearch:
        class: Wikipedia\Engine
        arguments:
            - '@acme.article_repository'
            - '@acme.wikiclient'
            - '%acme.wikisearch.api%'

    acme.wikiclient:
        class: Wikipedia\Client
